-- Archivo legacy (MySQL)
--
-- Este proyecto fue migrado a PostgreSQL para Render.
-- Usa `postgres_events.sql` para crear los jobs de agregación.
--
-- Si necesitas el script histórico de MySQL, avísame y te lo separo en un archivo .md
-- para no generar errores del validador SQL actual.
